spring.application.name=HailemariamBrendon.com

spring.datasource.url=jdbc:mysql://localhost:3306/hailemariam_brendon_com
spring.datasource.username=${USER_NAME}
spring.datasource.password=${SECRET_KEY}